# Generated by Django 2.0.13 on 2023-04-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_password', models.CharField(max_length=100)),
                ('u_name', models.CharField(max_length=100)),
                ('u_gender', models.CharField(max_length=10)),
                ('u_birth', models.DateTimeField()),
                ('c_id', models.IntegerField()),
            ],
        ),
    ]
