# Generated by Django 2.0.13 on 2023-04-23 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_name', models.CharField(max_length=100, unique=True)),
                ('r_type', models.CharField(max_length=100)),
                ('r_price', models.IntegerField(max_length=10)),
                ('r_address', models.CharField(max_length=254)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.City')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_password', models.CharField(max_length=100)),
                ('u_name', models.CharField(max_length=100)),
                ('u_gender', models.CharField(max_length=10)),
                ('u_birth', models.DateTimeField()),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.City')),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.AddField(
            model_name='record',
            name='r_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.Restaurant'),
        ),
        migrations.AddField(
            model_name='record',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MM.User'),
        ),
    ]
