# Generated by Django 2.0.13 on 2023-04-23 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MM', '0002_auto_20230423_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='c_name',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='r_id',
            new_name='r',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='u_id',
            new_name='u',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='c_id',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='c_id',
            new_name='c',
        ),
    ]
